public class test {
    //public test(){
		/* List<String> li=new List<String>{'Tanu','tanisha','ananya','preeti'};
        List<String> lis=new List<String>{'goswami','jain','agrawal','sharma'};
		Li.add('tiger');
		li.add(0,'cheetah');
		System.debug(li);
        li.addAll(lis);
        System.debug(li); 
        
        Map<Integer,String> mp=new Map<Integer,String>();
        mp.put(1,'tanu');
        System.debug(mp);*/
        
       //public enum Season{'WINTER', 'SPRING', 'SUMMER', 'FALL'};
        public enum Season {WINTER, SPRING, SUMMER, FALL}
    	
            
    
}